# Generated by Django 6.0.4 on 2026-05-16 11:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_alter_cinema_description_alter_cinema_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='contacts',
            field=models.CharField(default='+380 (44) 123-45-67', max_length=100, verbose_name='Contacts'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='location',
            field=models.CharField(default='Main Street, 1', max_length=255, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='working_hours',
            field=models.CharField(default='10:00 - 22:00', max_length=100, verbose_name='Working Hours'),
        ),
        migrations.AddField(
            model_name='session',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='cinema.hall'),
        ),
        migrations.AddField(
            model_name='session',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Time'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField(verbose_name='Seat Number')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='Purchased At')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='cinema.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
